dist: trusty
sudo: false
language: python
python:
    - "3.4"
install:
    - pip install tox
script:
    - tox
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build/doc/
    on:
        branch: master
